# Generated by Django 5.2 on 2025-05-28 16:47

import apps.core.models.validators.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(verbose_name=50)),
                ('account_number', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=5)),
                ('flat', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=21)),
                ('contact_value', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(verbose_name=50)),
                ('service_description', models.CharField(verbose_name=50)),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(verbose_name=21)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('surname', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=21)),
                ('patronymic', models.CharField(max_length=21)),
                ('birthday', models.DateField(validators=[apps.core.models.validators.validators.validate_not_future])),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('accounts', models.ManyToManyField(related_name='clients', to='core.account')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('contacts', models.ManyToManyField(related_name='clients', to='core.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_from', models.DateTimeField()),
                ('time_till', models.DateTimeField()),
                ('appointment_details', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_completed', models.BooleanField(verbose_name=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=21)),
                ('patronymic', models.CharField(max_length=21)),
                ('birthday', models.DateField(validators=[apps.core.models.validators.validators.validate_not_future])),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(related_name='specialists', to='core.client')),
                ('contacts', models.ManyToManyField(related_name='workers', to='core.contact')),
                ('specialities', models.ManyToManyField(related_name='specialists', to='core.speciality')),
            ],
        ),
    ]
