# Generated by Django 5.2 on 2025-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='speciality',
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialities',
            field=models.ManyToManyField(related_name='specialists', to='core.speciality'),
        ),
    ]
