# Generated by Django 5.2 on 2025-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('worker', 'Worker'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
